# Generated by Django 5.2.1 on 2025-05-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mesure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField()),
                ("humidite", models.FloatField()),
                ("qualite_air", models.IntegerField()),
                ("niveau_air", models.CharField(max_length=20)),
                ("date_recue", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
