# Generated by Django 5.2.3 on 2025-07-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capteurs", "0002_mesure_mois_mesure_periode_encoded_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mesure",
            name="humidite_sol",
            field=models.FloatField(
                default=0.0, help_text="Humidité du sol en pourcentage (0-100%)"
            ),
        ),
        migrations.AddField(
            model_name="mesure",
            name="niveau_sol",
            field=models.CharField(
                default="inconnu",
                help_text="Niveau: très sec, assez sec, humide, très humide",
                max_length=20,
            ),
        ),
    ]
